const deliveryTeste = [
  {
    "local_id": 1,
    "setor_id": 8,
    "descricao_setor": "SECRETARIA DE EDUCACAO",
    "descricao": "SECRETARIA DE EDUCAÇÃO",
    "endereco": "Não Informado",
    "latitude": "-23.87875461484137",
    "longitude": "-47.99343241843717",
    "responsavel_id": 1,
    "nome_local": "Recursos Humanos",
    "telefone_local": "+551532798008",
    "email_local": "rh@saomiguelarcanjo.sp.gov.br",
    "data_maxima": "2024-04-23",
    "resultado": 0,
    "datahora_resultado": null,
    "entrega_id": 1,
    "datahora_entrega": "2024-04-16 15:05:42",
    "parcial_total": 1,
    "nome_entrega": "JOAO DA EDUCACAO",
    "observacao": "ENTREGUE OS DOCUMENTOS NO SETOR DE RECURSOS HUMANOS",
    "usuario_id_entrega": 1,
    "auth_dados": true
  },
  {
    "local_id": 1,
    "setor_id": 8,
    "descricao_setor": "SECRETARIA DE EDUCACAO",
    "descricao": "SECRETARIA DE EDUCAÇÃO",
    "endereco": "Não Informado",
    "latitude": "-23.87875461484137",
    "longitude": "-47.99343241843717",
    "responsavel_id": 1,
    "nome_local": "Recursos Humanos",
    "telefone_local": "+551532798008",
    "email_local": "rh@saomiguelarcanjo.sp.gov.br",
    "data_maxima": "2024-04-23",
    "resultado": 0,
    "datahora_resultado": null,
    "entrega_id": 2,
    "datahora_entrega": "2024-04-16 15:05:42",
    "parcial_total": 1,
    "nome_entrega": "JOAO DA EDUCACAO",
    "observacao": "ENTREGUE OS DOCUMENTOS NO SETOR DE RECURSOS HUMANOS",
    "usuario_id_entrega": 1,
    "auth_dados": true
  },
  {
    "local_id": 1,
    "setor_id": 8,
    "descricao_setor": "SECRETARIA DE EDUCACAO",
    "descricao": "SECRETARIA DE EDUCAÇÃO",
    "endereco": "Não Informado",
    "latitude": "-23.87875461484137",
    "longitude": "-47.99343241843717",
    "responsavel_id": 1,
    "nome_local": "Recursos Humanos",
    "telefone_local": "+551532798008",
    "email_local": "rh@saomiguelarcanjo.sp.gov.br",
    "data_maxima": "2024-04-23",
    "resultado": 0,
    "datahora_resultado": null,
    "entrega_id": 3,
    "datahora_entrega": "2024-04-16 15:05:42",
    "parcial_total": 1,
    "nome_entrega": "JOAO DA EDUCACAO",
    "observacao": "ENTREGUE OS DOCUMENTOS NO SETOR DE RECURSOS HUMANOS",
    "usuario_id_entrega": 1,
    "auth_dados": true
  },
  {
    "local_id": 1,
    "setor_id": 8,
    "descricao_setor": "SECRETARIA DE EDUCACAO",
    "descricao": "SECRETARIA DE EDUCAÇÃO",
    "endereco": "Não Informado",
    "latitude": "-23.87875461484137",
    "longitude": "-47.99343241843717",
    "responsavel_id": 1,
    "nome_local": "Recursos Humanos",
    "telefone_local": "+551532798008",
    "email_local": "rh@saomiguelarcanjo.sp.gov.br",
    "data_maxima": "2024-04-23",
    "resultado": 0,
    "datahora_resultado": null,
    "entrega_id": 4,
    "datahora_entrega": "2024-04-16 15:05:42",
    "parcial_total": 1,
    "nome_entrega": "JOAO DA EDUCACAO",
    "observacao": "ENTREGUE OS DOCUMENTOS NO SETOR DE RECURSOS HUMANOS",
    "usuario_id_entrega": 4,
    "auth_dados": true
  },
  {
    "local_id": 1,
    "setor_id": 8,
    "descricao_setor": "SECRETARIA DE EDUCACAO",
    "descricao": "SECRETARIA DE EDUCAÇÃO",
    "endereco": "Não Informado",
    "latitude": "-23.87875461484137",
    "longitude": "-47.99343241843717",
    "responsavel_id": 1,
    "nome_local": "Recursos Humanos",
    "telefone_local": "+551532798008",
    "email_local": "rh@saomiguelarcanjo.sp.gov.br",
    "data_maxima": "2024-04-23",
    "resultado": 0,
    "datahora_resultado": null,
    "entrega_id": 1,
    "datahora_entrega": "2024-04-16 15:05:42",
    "parcial_total": 1,
    "nome_entrega": "JOAO DA EDUCACAO",
    "observacao": "ENTREGUE OS DOCUMENTOS NO SETOR DE RECURSOS HUMANOS",
    "usuario_id_entrega": 1,
    "auth_dados": true
  },
  {
    "local_id": 1,
    "setor_id": 8,
    "descricao_setor": "SECRETARIA DE EDUCACAO",
    "descricao": "SECRETARIA DE EDUCAÇÃO",
    "endereco": "Não Informado",
    "latitude": "-23.87875461484137",
    "longitude": "-47.99343241843717",
    "responsavel_id": 1,
    "nome_local": "Recursos Humanos",
    "telefone_local": "+551532798008",
    "email_local": "rh@saomiguelarcanjo.sp.gov.br",
    "data_maxima": "2024-04-23",
    "resultado": 0,
    "datahora_resultado": null,
    "entrega_id": 3,
    "datahora_entrega": "2024-04-16 15:05:42",
    "parcial_total": 1,
    "nome_entrega": "JOAO DA EDUCACAO",
    "observacao": "ENTREGUE OS DOCUMENTOS NO SETOR DE RECURSOS HUMANOS",
    "usuario_id_entrega": 1,
    "auth_dados": true
  },
  {
    "local_id": 1,
    "setor_id": 8,
    "descricao_setor": "SECRETARIA DE EDUCACAO",
    "descricao": "SECRETARIA DE EDUCAÇÃO",
    "endereco": "Não Informado",
    "latitude": "-23.87875461484137",
    "longitude": "-47.99343241843717",
    "responsavel_id": 1,
    "nome_local": "Recursos Humanos",
    "telefone_local": "+551532798008",
    "email_local": "rh@saomiguelarcanjo.sp.gov.br",
    "data_maxima": "2024-04-23",
    "resultado": 0,
    "datahora_resultado": null,
    "entrega_id": 4,
    "datahora_entrega": "2024-04-16 15:05:42",
    "parcial_total": 1,
    "nome_entrega": "JOAO DA EDUCACAO",
    "observacao": "ENTREGUE OS DOCUMENTOS NO SETOR DE RECURSOS HUMANOS",
    "usuario_id_entrega": 4,
    "auth_dados": true
  }
]

const departments = [
  { id: 1, name: "SECRETARIA DE EDUCAÇÃO" },
  { id: 2, name: "OFICINA PEDAGÓGICA MUNICIPAL" },
  { id: 3, name: "DEPARTAMENTO DE ESPORTES" },
  { id: 4, name: "ASSOCIAÇÃO DE PAIS E AMIGOS DOS EXCEPCIONAIS DE SMA - APAE" },
  { id: 5, name: "CERI 'PROF. ARY MONTEIRO GALVÃO'" },
  { id: 6, name: "CRECHE MUNICIPAL 'CELESTINA BERTIN DE ALMEIDA' / I, II e III" },
  { id: 7, name: "E.M.E.F. ' PROF. ARANI JOSÉ DA SILVA'" },
  { id: 8, name: "E.M.E.F. 'PROF. ARCYPRESTES RUGGERI'" },
  { id: 9, name: "E.M.E.I.F. 'ANGELINA MIGUEL ARUK'" },
  { id: 10, name: "E.M.E.I.F. 'FERMINO MENDES DA SILVA'" },
  { id: 11, name: "E.M.E.I.F. 'JOAQUIM NUNES VIEIRA'" },
  { id: 12, name: "E.M.E.I.F. 'JOSÉ GOMIDE DE CASTRO'" },
  { id: 13, name: "E.M.E.I.F. 'LEONARDO ANTONIO VIEIRA'" },
  { id: 14, name: "E.M.E.I.F. 'PROF. LUIZ FERNANDO CORREA PIRES'" },
  { id: 15, name: "E.M.E.I.F. 'PAULO ORTIZ DE CAMARGO'" },
  { id: 16, name: "E.M.E.I.F. 'PROFª CARMELITA VIEIRA TERRA DIAS'" },
  { id: 17, name: "E.M.E.I.F. 'PROFª MARIA INÊS MARQUES MENDES'" },
  { id: 18, name: "E.M.E.I.F. 'THEREZA MARIA DA CUNHA BODO DE CARVALHO'" },
  { id: 19, name: "E.M.E.I.F. 'VEREADOR JOÃO GATO'" },
  { id: 20, name: "E.M.E.I.F. 'VEREADOR JOSÉ CAMARGO'" },
  { id: 21, name: "E.M.E.I.F. 'NELSON RODRIGUES'" },
  { id: 22, name: "C.M.E.I.F. 'MARIA DE LOURDES FOGAÇA'" },
  { id: 23, name: "CRECHE MUNICIPAL 'PROF.ª EVANI FRANÇA DE ARAÚJO'" },
  { id: 24, name: "CRECHE NELSON SOARES" },
  { id: 25, name: "ASSISTÊNCIA SOCIAL" },
  { id: 26, name: "CRAS" },
  { id: 27, name: "CREAS" },
  { id: 28, name: "CADASTRO ÚNICO" },
  { id: 29, name: "CASA DA CRIANÇA" },
  { id: 30, name: "TRÂNSITO" },
  { id: 31, name: "AGRICULTURA" }
]

const deliveryStatus = [
  {
    statusId: 1,
    status: 'Conferido'
  },
  {
    statusId: 2,
    status: 'Entrega Parcial'
  },{
    statusId: 3,
    status: 'Entregue'
  },{
    statusId: 4,
    status: 'Não Entregue'
  },
]


export {deliveryTeste, departments, deliveryStatus}